version: '3'
services:
    ventilator:
        build: .
        volumes:
            - ./ventilator/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/ventilator.jar"]
        links:
          - sink
        depends_on:
          - sink


    worker:
        build: .
        volumes:
            - ./worker/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/worker.jar"]
        links:
          - ventilator
          - sink
        depends_on:
          - sink

    worker2:
        build: .
        volumes:
            - ./worker/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/worker.jar"]
        links:
          - ventilator
          - sink
        depends_on:
          - sink

    worker3:
        build: .
        volumes:
            - ./worker/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/worker.jar"]
        links:
          - ventilator
          - sink
        depends_on:
          - sink

    sink:
        build: .
        volumes:
            - ./sink/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/sink.jar"]