version: '3'
services:
    requester:
        build: .
        volumes:
            - ./requester/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/requester.jar"]


    responder:
        build: .
        volumes:
            - ./responder/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/responder.jar"]
        ports:
          - 5555:5555
        links:
          - requester